"use client"

import type {
  CsvColumnLetter,
  ImportMappingConfig,
  ImportMappingEntry,
} from "@/types/firestore-models"

import { createEmptyMappingEntry } from "./import-mapping-types"

type DefaultEntryOptions = Partial<ImportMappingEntry> & {
  column: CsvColumnLetter
  name: string
}

function defaultEntry({
  column,
  name,
  format = "original",
  formatConditions = [format],
  hideInCompactView = false,
  includeInCsvDownload = true,
  ...entry
}: DefaultEntryOptions): ImportMappingEntry {
  return createEmptyMappingEntry({
    id: `standard-${column.toLowerCase()}`,
    targetColumns: [column],
    targetColumnName: name,
    format,
    formatConditions,
    hideInCompactView,
    includeInCsvDownload,
    ...entry,
  })
}

export function createDefaultImportMappingConfig(): ImportMappingConfig {
  return {
    id: "standard-mapping",
    name: "標準マッピング",
    description: "標準の受注ファイル形式に対応する初期設定です。",
    startDetailRow: 16,
    validRowColumn: "R",
    active: true,
    deleted: false,
    version: 1,
    customerRule: "ALL",
    entries: [
      defaultEntry({
        column: "A",
        name: "会社コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "K4",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "B",
        name: "伝票識別番号",
        dataSource: "blank",
        scope: "sheet",
      }),
      defaultEntry({
        column: "C",
        name: "分納区分",
        dataSource: "fixedValue",
        fixedValue: "0",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "D",
        name: "取引区分",
        dataSource: "fixedValue",
        fixedValue: "01",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "E",
        name: "得意先コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "D4",
        scope: "sheet",
      }),
      defaultEntry({
        column: "F",
        name: "得意先名１",
        dataSource: "masterLookup",
        lookupCsvColumn: "E",
        lookupCollection: "CusCodeList",
        lookupKeyField: "得意先コード",
        lookupValueField: "得意先名",
        lookupTargetColumn: "F",
        scope: "detail",
      }),
      defaultEntry({
        column: "G",
        name: "得意先略名１",
        dataSource: "masterLookup",
        lookupCsvColumn: "E",
        lookupCollection: "CusCodeList",
        lookupKeyField: "得意先コード",
        lookupValueField: "得意先略名",
        lookupTargetColumn: "G",
        hideInCompactView: true,
        scope: "detail",
      }),
      defaultEntry({
        column: "H",
        name: "得意先住所",
        dataSource: "masterLookup",
        lookupCsvColumn: "E",
        lookupCollection: "CusCodeList",
        lookupKeyField: "得意先コード",
        lookupValueField: "得意先・納入先住所",
        lookupTargetColumn: "H",
        formatConditions: ["original", "left32"],
        hideInCompactView: true,
        scope: "detail",
      }),
      defaultEntry({
        column: "I",
        name: "請求先コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "D4",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "J",
        name: "売掛先コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "D4",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "K",
        name: "納入先コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "K8",
        scope: "sheet",
      }),
      defaultEntry({
        column: "L",
        name: "納入先名１",
        dataSource: "masterLookup",
        lookupCsvColumn: "K",
        lookupCollection: "CusCodeList",
        lookupKeyField: "得意先コード",
        lookupValueField: "得意先名",
        lookupTargetColumn: "L",
        hideInCompactView: true,
        scope: "detail",
      }),
      defaultEntry({
        column: "M",
        name: "納入先略名１",
        dataSource: "masterLookup",
        lookupCsvColumn: "K",
        lookupCollection: "CusCodeList",
        lookupKeyField: "得意先コード",
        lookupValueField: "得意先略名",
        lookupTargetColumn: "M",
        hideInCompactView: true,
        scope: "detail",
      }),
      defaultEntry({
        column: "N",
        name: "納入先住所",
        dataSource: "masterLookup",
        lookupCsvColumn: "K",
        lookupCollection: "CusCodeList",
        lookupKeyField: "得意先コード",
        lookupValueField: "得意先・納入先住所",
        lookupTargetColumn: "N",
        formatConditions: ["original", "left32"],
        hideInCompactView: true,
        scope: "detail",
      }),
      defaultEntry({
        column: "O",
        name: "売上担当者コード",
        dataSource: "manualInput",
        scope: "sheet",
      }),
      defaultEntry({
        column: "P",
        name: "売上計上部門コード",
        dataSource: "fixedValue",
        fixedValue: "TK11",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "Q",
        name: "売上取引形態区分",
        dataSource: "fixedValue",
        fixedValue: "1",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "R",
        name: "売上計上基準区分",
        dataSource: "fixedValue",
        fixedValue: "1",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "S",
        name: "請求帳端区分",
        dataSource: "fixedValue",
        fixedValue: "1",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "T",
        name: "倉庫コード",
        dataSource: "masterLookup",
        lookupCsvColumn: "O",
        lookupCollection: "PIC.WH.CodeList",
        lookupKeyField: "担当者コード",
        lookupValueField: "倉庫コード",
        lookupTargetColumn: "T",
        hideInCompactView: true,
        scope: "detail",
      }),
      defaultEntry({
        column: "U",
        name: "取引通貨コード",
        dataSource: "fixedValue",
        fixedValue: "JPY",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "V",
        name: "明細取引通貨コード",
        dataSource: "fixedValue",
        fixedValue: "JPY",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "W",
        name: "受注日",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "Q5",
        format: "date",
        formatConditions: ["date"],
        scope: "sheet",
      }),
      defaultEntry({
        column: "X",
        name: "出荷予定日",
        dataSource: "orderFile",
        orderFileMode: "sourceFormula",
        sourceDataKind: "number",
        sourcePosition: "Q7",
        sourceFormula: "Q7 - 1",
        format: "date",
        formatConditions: ["date"],
        scope: "sheet",
      }),
      defaultEntry({
        column: "Y",
        name: "納品予定日",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "Q7",
        format: "date",
        formatConditions: ["date"],
        scope: "sheet",
      }),
      defaultEntry({
        column: "Z",
        name: "拡張コード項目２",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "C",
        scope: "detail",
      }),
      defaultEntry({
        column: "AA",
        name: "拡張コード項目３",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "I",
        formatConditions: ["alphanumericOnly"],
        scope: "detail",
      }),
      defaultEntry({
        column: "AB",
        name: "拡張テキスト項目１",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "E",
        scope: "detail",
      }),
      defaultEntry({
        column: "AC",
        name: "備考",
        dataSource: "blank",
        scope: "sheet",
      }),
      defaultEntry({
        column: "AD",
        name: "売上伝票行番号",
        dataSource: "formula",
        formula: "=ROW_NUMBER",
        hideInCompactView: true,
        scope: "system",
      }),
      defaultEntry({
        column: "AE",
        name: "手配区分",
        dataSource: "fixedValue",
        fixedValue: "1",
        hideInCompactView: true,
        scope: "sheet",
      }),
      defaultEntry({
        column: "AF",
        name: "商品コード",
        dataSource: "masterLookup",
        lookupCsvColumn: "AQ",
        lookupCollection: "ItemCodeListMAV",
        lookupKeyField: "工場資材コード(MAV)",
        lookupValueField: "伊豆義(日本）コード",
        lookupTargetColumn: "AF",
        scope: "detail",
      }),
      defaultEntry({
        column: "AG",
        name: "商品名",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "M",
        formatConditions: ["original", "left25"],
        scope: "detail",
      }),
      defaultEntry({
        column: "AH",
        name: "サイズ",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "O",
        includeInCsvDownload: false,
        scope: "detail",
      }),
      defaultEntry({
        column: "AI",
        name: "明細倉庫コード",
        dataSource: "masterLookup",
        lookupCsvColumn: "O",
        lookupCollection: "PIC.WH.CodeList",
        lookupKeyField: "担当者コード",
        lookupValueField: "明細倉庫コード",
        lookupTargetColumn: "AI",
        scope: "detail",
      }),
      defaultEntry({
        column: "AJ",
        name: "受注数",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "R",
        scope: "detail",
      }),
      defaultEntry({
        column: "AK",
        name: "単位コード",
        dataSource: "masterLookup",
        lookupCsvColumn: "AR",
        lookupCollection: "UnitCodeList",
        lookupKeyField: "OrderUnit",
        lookupValueField: "CsvCode",
        lookupTargetColumn: "AK",
        scope: "detail",
      }),
      defaultEntry({
        column: "AL",
        name: "受注単価",
        dataSource: "masterLookup",
        lookupCsvColumn: "AF",
        lookupCollection: "ItemCodeListMAV",
        lookupKeyField: "伊豆義(日本）コード",
        lookupValueField: "伊豆義(日本）コード",
        lookupTargetColumn: "AL",
        scope: "detail",
      }),
      defaultEntry({
        column: "AM",
        name: "明細受注金額",
        dataSource: "formula",
        formula: "=AL*AJ",
        format: "number",
        formatConditions: ["numberIntegerTruncate"],
        scope: "system",
      }),
      defaultEntry({
        column: "AN",
        name: "取引通貨受注単価",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "U",
        hideInCompactView: true,
        scope: "detail",
      }),
      defaultEntry({
        column: "AO",
        name: "取引通貨明細受注金額",
        dataSource: "formula",
        formula: "=AN*AJ",
        format: "number",
        formatConditions: ["numberIntegerTruncate"],
        hideInCompactView: true,
        scope: "system",
      }),
      defaultEntry({
        column: "AP",
        name: "引当予定日",
        dataSource: "orderFile",
        orderFileMode: "sourceFormula",
        sourceDataKind: "number",
        sourcePosition: "Q7",
        sourceFormula: "Q7 - 1",
        format: "date",
        formatConditions: ["date"],
        scope: "sheet",
      }),
      defaultEntry({
        column: "AQ",
        name: "ベトナム工場の資材コード",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "L",
        includeInCsvDownload: false,
        scope: "detail",
      }),
      defaultEntry({
        column: "AR",
        name: "単位コード(工場）",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "S",
        includeInCsvDownload: false,
        scope: "detail",
      }),
    ],
  }
}
